### PR TITLE
Update underlying color with setting alpha and opacity, and re-structure as library.

### LINKED ISSUE #3: setAlpha and setOpacity have no effect
### Summary

The `setAlpha` and `setOpacity` methods don't seem to have any effect on the `TinyColor` instance.

### Possible cause

Looking at the source, I believe this is because these methods [are defined like this](https://github.com/FooStudio/tinycolor/blob/717a603a6e3a35b693e8b0dab15384a954067034/lib/tinycolor.dart#L59-L62):

```js
TinyColor setAlpha(int alpha) {
  _color.withAlpha(alpha);
  return this;
}
```

However, the `withAlpha` method [returns a _new_ `Color` instance](https://api.flutter.dev/flutter/dart-ui/Color/withAlpha.html):

> Returns a new color that matches this color with the alpha channel replaced with a (which ranges from 0 to 255).

so this doesn't actually change `_color`.

### Context

This bug was originally submitted to https://github.com/FooStudio/tinycolor/issues/14 and was copied here.

### PR DESCRIPTION
**Pull request by TNorbury**
`_color` field inside of the `TinyColor` object is now updated when setting the alpha or opacity.

Added relevant tests.

Also updated an import inside of an already existing test while I was here.

closes #3 

P.S. I also know that stuff is still getting set up, so lmk if ya need me to update my PR to work with lints or CI.

### CODE REVIEW

**Review by calvintam236 — DISMISSED** [review]

**Comment by JamesMcIntosh** [comment]
Hi @calvintam236, have you been in contact with FooStudio/Ricardo Mendieta about taking over management of the original repository?
Is this repo fork going to be published to pub.dev?

**Comment by WieFel** [comment]
> Hi @calvintam236, have you been in contact with FooStudio/Ricardo Mendieta about taking over management of the original repository?
> Is this repo fork going to be published to pub.dev?

@JamesMcIntosh we tried to contact them and waited for a while but they don't seem to answer.
We want to publish this on pub.dev, yes! ;)

**Comment by TNorbury** [comment]
merged in #5

**Comment by JamesMcIntosh** [comment]
> > Hi @calvintam236, have you been in contact with FooStudio/Ricardo Mendieta about taking over management of the original repository?
> > Is this repo fork going to be published to pub.dev?
> 
> @JamesMcIntosh we tried to contact them and waited for a while but they don't seem to answer.
> We want to publish this on pub.dev, yes! ;)

Thanks Felix, I've sent @mendieta an email at FooStudio and a message on Linked-In too, he's definitely still around as he's committing almost daily to private repositories on GitHub...

**Comment by calvintam236** [comment]
@TNorbury @WieFel Since null safety PR is still not yet here, let’s merge this and get the example project up to date as well.

**Review by calvintam236 — APPROVED** [review]

**Pull request merged**
