### PR TITLE
Rewrite tests

### PR DESCRIPTION
**Pull request by calvintam236**

### CODE REVIEW

**Comment by calvintam236** [comment]
@WieFel Any good idea how to test all the setters?

**Comment by WieFel** [comment]
@calvintam236 probably the only way is to set some value and use the getters in the same way as you did in the getters tests

**Comment by calvintam236** [comment]
> @calvintam236 probably the only way is to set some value and use the getters in the same way as you did in the getters tests

@WieFel The problem is what are the expected value of each setter since they all return `TinyColor`.
For example, https://github.com/TinyCommunity/tinycolor2#lighten
Should it test `TinyColor.lighten() == Color.lighten(10)`?

**Comment by WieFel** [comment]
Not sure how to best test this...

Maybe check something like `color.lighten().darken() == color`.
Not sure whether this assumption actually holds or not.

**Comment by calvintam236** [comment]
> Not sure how to best test this...
> 
> Maybe check something like `color.lighten().darken() == color`. Not sure whether this assumption actually holds or not.

@WieFel I added the remaining tests by testing every methods independently. Should this sufficient?
Can you take a look if I made any logic error? (I hope not.)

**Review by WieFel — APPROVED** [review]
LGTM

**Pull request merged**
