### PR TITLE
Add .toHex8()

### PR DESCRIPTION
**Pull request by calvintam236**

### CODE REVIEW

**Comment by WieFel** [comment]
Quick question: What is the purpose of `toHex8()`?

**Comment by calvintam236** [comment]
> Quick question: What is the purpose of `toHex8()`?

matching original [`.toHex8()`](https://www.npmjs.com/package/tinycolor2)

**Comment by WieFel** [comment]
Ok 🤔 not sure if the implementation is correct, but you basically copied it from original, right?

**Comment by calvintam236** [comment]
> Ok 🤔 not sure if the implementation is correct, but you basically copied it from original, right?

Based on https://api.flutter.dev/flutter/dart-ui/Color/toString.html

**Review by WieFel — APPROVED** [review]

**Pull request merged**
